"""update document policy logic

Revision ID: 026135e26dbf
Revises: 0921218dd0a5
Create Date: 2026-08-08 00:12:41.619902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '026135e26dbf'
down_revision: Union[str, Sequence[str], None] = '0921218dd0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_access_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_access_policy_created_by', 'document_access_policies', ['created_by'], unique=False)
    op.create_index('idx_document_access_policy_document', 'document_access_policies', ['document_id'], unique=False)
    op.create_index('idx_document_access_policy_tenant', 'document_access_policies', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_document_access_policies_created_by'), 'document_access_policies', ['created_by'], unique=False)
    op.create_index(op.f('ix_document_access_policies_document_id'), 'document_access_policies', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_access_policies_id'), 'document_access_policies', ['id'], unique=False)
    op.create_index(op.f('ix_document_access_policies_tenant_id'), 'document_access_policies', ['tenant_id'], unique=False)
    op.create_table('access_policy_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('condition_type', sa.String(length=32), nullable=False),
    sa.Column('condition_value_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['document_access_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_policy_condition_policy', 'access_policy_conditions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_access_policy_conditions_id'), 'access_policy_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_access_policy_conditions_policy_id'), 'access_policy_conditions', ['policy_id'], unique=False)
    op.drop_index(op.f('idx_doc_role_access_role'), table_name='document_role_access')
    op.drop_table('document_role_access')
    op.drop_index(op.f('idx_doc_dept_access_dept'), table_name='document_department_access')
    op.drop_table('document_department_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_department_access',
    sa.Column('document_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('document_department_access_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_department_access_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'department_id', name=op.f('document_department_access_pkey'))
    )
    op.create_index(op.f('idx_doc_dept_access_dept'), 'document_department_access', ['department_id'], unique=False)
    op.create_table('document_role_access',
    sa.Column('document_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_role_access_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('document_role_access_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'role_id', name=op.f('document_role_access_pkey'))
    )
    op.create_index(op.f('idx_doc_role_access_role'), 'document_role_access', ['role_id'], unique=False)
    op.drop_index(op.f('ix_access_policy_conditions_policy_id'), table_name='access_policy_conditions')
    op.drop_index(op.f('ix_access_policy_conditions_id'), table_name='access_policy_conditions')
    op.drop_index('idx_access_policy_condition_policy', table_name='access_policy_conditions')
    op.drop_table('access_policy_conditions')
    op.drop_index(op.f('ix_document_access_policies_tenant_id'), table_name='document_access_policies')
    op.drop_index(op.f('ix_document_access_policies_id'), table_name='document_access_policies')
    op.drop_index(op.f('ix_document_access_policies_document_id'), table_name='document_access_policies')
    op.drop_index(op.f('ix_document_access_policies_created_by'), table_name='document_access_policies')
    op.drop_index('idx_document_access_policy_tenant', table_name='document_access_policies')
    op.drop_index('idx_document_access_policy_document', table_name='document_access_policies')
    op.drop_index('idx_document_access_policy_created_by', table_name='document_access_policies')
    op.drop_table('document_access_policies')
    # ### end Alembic commands ###
