"""update prompt_templates table

Revision ID: 0921218dd0a5
Revises: f1c96d67ad56
Create Date: 2026-08-07 15:37:04.695600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0921218dd0a5'
down_revision: Union[str, Sequence[str], None] = 'f1c96d67ad56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('type', sa.String(length=64), nullable=False))
    op.add_column('prompt_templates', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('prompt_templates', sa.Column('description', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_prompt_templates_tenant_agent_active'), table_name='prompt_templates')
    op.create_index('idx_prompt_templates_tenant_type_active', 'prompt_templates', ['tenant_id', 'type', 'is_active'], unique=False)
    op.drop_column('prompt_templates', 'agent_type')
    op.drop_column('prompt_templates', 'user_prompt')
    op.drop_column('prompt_templates', 'variables')
    op.drop_column('prompt_templates', 'system_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('prompt_templates', sa.Column('variables', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('prompt_templates', sa.Column('user_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('prompt_templates', sa.Column('agent_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index('idx_prompt_templates_tenant_type_active', table_name='prompt_templates')
    op.create_index(op.f('idx_prompt_templates_tenant_agent_active'), 'prompt_templates', ['tenant_id', 'agent_type', 'is_active'], unique=False)
    op.drop_column('prompt_templates', 'description')
    op.drop_column('prompt_templates', 'content')
    op.drop_column('prompt_templates', 'type')
    # ### end Alembic commands ###
