"""update nullable

Revision ID: 348f435cf4fb
Revises: 025dfaa1245d
Create Date: 2026-05-22 18:15:16.692519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348f435cf4fb'
down_revision: Union[str, Sequence[str], None] = '025dfaa1245d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'assigned_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
