"""add granted_at to document_role_access

Revision ID: 44d2a9a52a70
Revises: d399d9602213
Create Date: 2026-06-09 15:07:50.425396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d2a9a52a70'
down_revision: Union[str, Sequence[str], None] = 'd399d9602213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_role_access', sa.Column('granted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_role_access', 'granted_at')
    # ### end Alembic commands ###
