"""change column name in documents

Revision ID: 474ef327ba72
Revises: 6019515d5ef7
Create Date: 2026-06-03 22:52:57.990877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474ef327ba72'
down_revision: Union[str, Sequence[str], None] = '6019515d5ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('documents', 'department_scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('department_scope', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'department_id')
    # ### end Alembic commands ###
