"""update users table

Revision ID: 4dc8b9087c71
Revises: 21060e148c45
Create Date: 2026-06-23 18:00:27.768653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc8b9087c71'
down_revision: Union[str, Sequence[str], None] = '21060e148c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index('uq_global_admin_email', 'users', ['email'], unique=True, postgresql_where=sa.text('tenant_id IS NULL AND is_deleted = false'))
    op.create_index('uq_global_admin_employee_code', 'users', ['employee_code'], unique=True, postgresql_where=sa.text('tenant_id IS NULL AND is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_global_admin_employee_code', table_name='users', postgresql_where=sa.text('tenant_id IS NULL AND is_deleted = false'))
    op.drop_index('uq_global_admin_email', table_name='users', postgresql_where=sa.text('tenant_id IS NULL AND is_deleted = false'))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
