"""add document_department_access table

Revision ID: 57b6bb3664e8
Revises: 44d2a9a52a70
Create Date: 2026-06-12 17:53:31.115849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b6bb3664e8'
down_revision: Union[str, Sequence[str], None] = '44d2a9a52a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_department_access',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'department_id')
    )
    op.drop_constraint(op.f('documents_department_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_department_id_fkey'), 'documents', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_table('document_department_access')
    # ### end Alembic commands ###
