"""update user_sessions table

Revision ID: 5dcb39963faf
Revises: 8665f2042d8e
Create Date: 2026-06-26 21:53:59.807270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcb39963faf'
down_revision: Union[str, Sequence[str], None] = '8665f2042d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'user_agent')
    # ### end Alembic commands ###
