"""update user_sessions table

Revision ID: 6ad287bfc19e
Revises: 0b1ab66ca1e8
Create Date: 2026-05-31 23:33:49.396179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad287bfc19e'
down_revision: Union[str, Sequence[str], None] = '0b1ab66ca1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('jti', sa.String(), nullable=False))
    op.drop_column('user_sessions', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_sessions', 'jti')
    # ### end Alembic commands ###
