"""add document_role_access and update document status

Revision ID: 81e64c743dc8
Revises: 91f8ea53f66f
Create Date: 2026-05-27 12:08:01.346156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e64c743dc8'
down_revision: Union[str, Sequence[str], None] = '91f8ea53f66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=32),
               type_=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
