"""update documents, document_chunks and vector_embeddings table

Revision ID: 91f8ea53f66f
Revises: 348f435cf4fb
Create Date: 2026-05-27 11:38:40.978798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy.vector import VECTOR

# revision identifiers, used by Alembic.
revision: str = '91f8ea53f66f'
down_revision: Union[str, Sequence[str], None] = '348f435cf4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('context_content', sa.Text(), nullable=True))
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.alter_column('document_chunks', 'meta_data',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='meta_data::jsonb',
               existing_nullable=True)
    op.alter_column('document_chunks', 'embedding_model',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index(op.f('ix_document_chunks_embedding_model'), 'document_chunks', ['embedding_model'], unique=False)
    op.alter_column('documents', 'uploader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'access_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('documents', 'meta_data',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='meta_data::jsonb',
               existing_nullable=True)
    op.add_column('vector_embeddings', sa.Column('dimensions', sa.Integer(), nullable=False))
    op.alter_column('vector_embeddings', 'embedding',
               existing_type=VECTOR(dim=1536),
               type_=VECTOR(dim=1024),
               existing_nullable=False)
    op.drop_column('vector_embeddings', 'dimentions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_embeddings', sa.Column('dimentions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('vector_embeddings', 'embedding',
               existing_type=VECTOR(dim=1024),
               type_=VECTOR(dim=1536),
               existing_nullable=False)
    op.drop_column('vector_embeddings', 'dimensions')
    op.alter_column('documents', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'access_level',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('documents', 'uploader_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_document_chunks_embedding_model'), table_name='document_chunks')
    op.alter_column('document_chunks', 'embedding_model',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('document_chunks', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('document_chunks', 'chunk_index')
    op.drop_column('document_chunks', 'context_content')
    # ### end Alembic commands ###
