"""add documents column

Revision ID: ae3d7339a573
Revises: f9df6099722b
Create Date: 2026-05-29 21:08:52.418946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3d7339a573'
down_revision: Union[str, Sequence[str], None] = 'f9df6099722b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('category', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'effective_date')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
