"""add_partial_unique_indexes

Revision ID: b19567b2de72
Revises: dd99e464dc61
Create Date: 2026-06-18 12:01:09.444999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19567b2de72'
down_revision: Union[str, Sequence[str], None] = 'dd99e464dc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('uq_dept_tenant_code'), 'departments', type_='unique')
    op.drop_constraint(op.f('uq_dept_tenant_name'), 'departments', type_='unique')
    op.create_index('uq_dept_tenant_code_active', 'departments', ['tenant_id', 'code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_dept_tenant_name_active', 'departments', ['tenant_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_document_tenant_file_hash_active', 'documents', ['tenant_id', 'file_hash'], unique=True, postgresql_where=sa.text('is_deleted = false AND file_hash IS NOT NULL'))
    op.add_column('job_titles', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('uq_job_tenant_code'), 'job_titles', type_='unique')
    op.drop_constraint(op.f('uq_job_tenant_title_name'), 'job_titles', type_='unique')
    op.create_index('uq_job_tenant_code_active', 'job_titles', ['tenant_id', 'code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_job_tenant_title_name_active', 'job_titles', ['tenant_id', 'title_name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.add_column('roles', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('uq_role_tenant_name'), 'roles', type_='unique')
    op.create_index('uq_role_tenant_name_active', 'roles', ['tenant_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.drop_constraint(op.f('tenants_company_email_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_tenant_domain'), table_name='tenants')
    op.create_index(op.f('ix_tenants_tenant_domain'), 'tenants', ['tenant_domain'], unique=False)
    op.create_index('uq_tenant_company_email_active', 'tenants', ['company_email'], unique=True, postgresql_where=sa.text("status != 'deleted'"))
    op.create_index('uq_tenant_domain_active', 'tenants', ['tenant_domain'], unique=True, postgresql_where=sa.text("status != 'deleted'"))
    op.drop_constraint(op.f('uq_user_tenant_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_user_tenant_employee_code'), 'users', type_='unique')
    op.create_index('uq_user_tenant_email_active', 'users', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_user_tenant_employee_code_active', 'users', ['tenant_id', 'employee_code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_tenant_employee_code_active', table_name='users', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_user_tenant_email_active', table_name='users', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_user_tenant_employee_code'), 'users', ['tenant_id', 'employee_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_tenant_email'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_tenant_domain_active', table_name='tenants', postgresql_where=sa.text("status != 'deleted'"))
    op.drop_index('uq_tenant_company_email_active', table_name='tenants', postgresql_where=sa.text("status != 'deleted'"))
    op.drop_index(op.f('ix_tenants_tenant_domain'), table_name='tenants')
    op.create_index(op.f('ix_tenants_tenant_domain'), 'tenants', ['tenant_domain'], unique=True)
    op.create_unique_constraint(op.f('tenants_company_email_key'), 'tenants', ['company_email'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_role_tenant_name_active', table_name='roles', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_role_tenant_name'), 'roles', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'is_deleted')
    op.drop_index('uq_job_tenant_title_name_active', table_name='job_titles', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_job_tenant_code_active', table_name='job_titles', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_job_tenant_title_name'), 'job_titles', ['tenant_id', 'title_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_job_tenant_code'), 'job_titles', ['tenant_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_column('job_titles', 'is_deleted')
    op.drop_index('uq_document_tenant_file_hash_active', table_name='documents', postgresql_where=sa.text('is_deleted = false AND file_hash IS NOT NULL'))
    op.drop_index('uq_dept_tenant_name_active', table_name='departments', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_dept_tenant_code_active', table_name='departments', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_dept_tenant_name'), 'departments', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_dept_tenant_code'), 'departments', ['tenant_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_column('departments', 'is_deleted')
    # ### end Alembic commands ###
