"""update activity log table

Revision ID: b78897dd46f9
Revises: dfa1bd0369b1
Create Date: 2026-06-22 15:31:15.111322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b78897dd46f9'
down_revision: Union[str, Sequence[str], None] = 'dfa1bd0369b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('log_level', sa.String(length=32), nullable=False))
    op.add_column('activity_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('activity_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('activity_logs', 'meta_data',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='meta_data::jsonb',
               existing_nullable=True)
    op.create_index('idx_activity_logs_global_created', 'activity_logs', ['created_at'], unique=False, postgresql_where=sa.text('tenant_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_logs_global_created', table_name='activity_logs', postgresql_where=sa.text('tenant_id IS NULL'))
    op.alter_column('activity_logs', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('activity_logs', 'is_deleted')
    op.drop_column('activity_logs', 'log_level')
    # ### end Alembic commands ###
