"""update schema

Revision ID: d95980d8ce56
Revises: 81e64c743dc8
Create Date: 2026-05-27 20:46:34.068356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95980d8ce56'
down_revision: Union[str, Sequence[str], None] = '81e64c743dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_document_chunk_index', 'document_chunks', ['document_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_document_chunk_index', 'document_chunks', type_='unique')
    # ### end Alembic commands ###
