"""update tenant table

Revision ID: dd99e464dc61
Revises: c0b1e9019f68
Create Date: 2026-06-18 10:44:16.878115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd99e464dc61'
down_revision: Union[str, Sequence[str], None] = 'c0b1e9019f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'tenant_domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_tenants_company_name'), table_name='tenants')
    op.drop_constraint(op.f('tenants_company_address_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_company_phone_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_tenant_domain_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_tenant_domain'), 'tenants', ['tenant_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_tenant_domain'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_tenant_domain_key'), 'tenants', ['tenant_domain'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_company_phone_key'), 'tenants', ['company_phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_company_address_key'), 'tenants', ['company_address'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tenants_company_name'), 'tenants', ['company_name'], unique=True)
    op.alter_column('tenants', 'tenant_domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
