"""add indexes

Revision ID: dfa1bd0369b1
Revises: b19567b2de72
Create Date: 2026-06-21 21:01:20.163313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa1bd0369b1'
down_revision: Union[str, Sequence[str], None] = 'b19567b2de72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_activity_logs_tenant_created', 'activity_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_activity_logs_user', 'activity_logs', ['user_id'], unique=False)
    op.create_index('idx_conversations_tenant_user_updated', 'conversations', ['tenant_id', 'user_id', 'updated_at'], unique=False)
    op.create_index('idx_document_chunks_tenant', 'document_chunks', ['tenant_id'], unique=False)
    op.create_index('idx_doc_dept_access_dept', 'document_department_access', ['department_id'], unique=False)
    op.create_index('idx_doc_role_access_role', 'document_role_access', ['role_id'], unique=False)
    op.create_index('idx_doc_user_access_user', 'document_user_access', ['user_id'], unique=False)
    op.create_index('idx_documents_tenant_deleted', 'documents', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index('idx_documents_uploader', 'documents', ['uploader_id'], unique=False)
    op.create_index('idx_embedding_jobs_doc', 'embedding_jobs', ['document_id'], unique=False)
    op.create_index('idx_embedding_jobs_status', 'embedding_jobs', ['status'], unique=False)
    op.create_index('idx_embedding_jobs_user', 'embedding_jobs', ['triggered_by'], unique=False)
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_prompt_templates_tenant_agent_active', 'prompt_templates', ['tenant_id', 'agent_type', 'is_active'], unique=False)
    op.create_index('idx_prompt_templates_user', 'prompt_templates', ['user_id'], unique=False)
    op.create_index('idx_role_permissions_permission', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_sessions_jti', 'user_sessions', ['jti'], unique=True)
    op.create_index('idx_user_sessions_tenant_user', 'user_sessions', ['tenant_id', 'user_id'], unique=False)
    op.create_index('idx_users_department', 'users', ['department_id'], unique=False)
    op.create_index('idx_users_job_title', 'users', ['job_title_id'], unique=False)
    op.create_index('idx_vector_embeddings_chunk', 'vector_embeddings', ['document_chunk_id'], unique=False)
    op.create_index('idx_vector_embeddings_hnsw', 'vector_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_vector_embeddings_tenant', 'vector_embeddings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vector_embeddings_tenant', table_name='vector_embeddings')
    op.drop_index('idx_vector_embeddings_hnsw', table_name='vector_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_vector_embeddings_chunk', table_name='vector_embeddings')
    op.drop_index('idx_users_job_title', table_name='users')
    op.drop_index('idx_users_department', table_name='users')
    op.drop_index('idx_user_sessions_tenant_user', table_name='user_sessions')
    op.drop_index('idx_user_sessions_jti', table_name='user_sessions')
    op.drop_index('idx_user_roles_role', table_name='user_roles')
    op.drop_index('idx_role_permissions_permission', table_name='role_permissions')
    op.drop_index('idx_prompt_templates_user', table_name='prompt_templates')
    op.drop_index('idx_prompt_templates_tenant_agent_active', table_name='prompt_templates')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_index('idx_embedding_jobs_user', table_name='embedding_jobs')
    op.drop_index('idx_embedding_jobs_status', table_name='embedding_jobs')
    op.drop_index('idx_embedding_jobs_doc', table_name='embedding_jobs')
    op.drop_index('idx_documents_uploader', table_name='documents')
    op.drop_index('idx_documents_tenant_deleted', table_name='documents')
    op.drop_index('idx_doc_user_access_user', table_name='document_user_access')
    op.drop_index('idx_doc_role_access_role', table_name='document_role_access')
    op.drop_index('idx_doc_dept_access_dept', table_name='document_department_access')
    op.drop_index('idx_document_chunks_tenant', table_name='document_chunks')
    op.drop_index('idx_conversations_tenant_user_updated', table_name='conversations')
    op.drop_index('idx_activity_logs_user', table_name='activity_logs')
    op.drop_index('idx_activity_logs_tenant_created', table_name='activity_logs')
    # ### end Alembic commands ###
