"""update activity_logs table

Revision ID: f1c96d67ad56
Revises: 45b1d5e9710c
Create Date: 2026-07-16 00:07:53.604163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1c96d67ad56'
down_revision: Union[str, Sequence[str], None] = '45b1d5e9710c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('user_agent', sa.String(length=512), nullable=True))
    op.drop_index(op.f('idx_document_chunks_content_tsv'), table_name='document_chunks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_document_chunks_content_tsv'), 'document_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.drop_column('activity_logs', 'user_agent')
    # ### end Alembic commands ###
