"""update documents file_type length and constraint

Revision ID: f9df6099722b
Revises: 79908295419f
Create Date: 2026-05-28 14:17:47.357436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9df6099722b'
down_revision: Union[str, Sequence[str], None] = '79908295419f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
